loop:
  gain: 0.5
  leakyGain: 0.0
  numDroppedModes: 0
  pokeAmp: 0.00000001 #10nm
  numItersIM: 4
  affinity: 2
  method: push-pull
  functions:
  - leakyIntegrator

wfs:
  name: OOPAOWFS
  width: 100
  height: 100
  darkCount: 0
  integration: 50
  affinity: 3
  functions:
  - expose

slopes:
  type: SHWFS
  signalType: slopes
  affinity: 3
  flatNorm: True
  subApSpacing: 10
  subApOffsetX: 0
  subApOffsetY: 0
  #Specify where the pupils are and how large for a PYWFS
  # pupilsRadius: 12
  # pupils:  
  # - 12,12
  # - 36,12
  # - 12,36
  # - 36,36
  functions:
  - computeSignal

wfc:
  name: "OOPAOWFC"
  numActuators: 101 
  numModes: 84
  flatFile: ""
  saveFile: "flat.npy"
  m2cFile:  ""
  affinity: 3
  commandCap: 10.0
  hardwareDelay: 0.001
  frameDelay: 0
  functions:
  - sendToHardware

psf:
  name: "OOPAOPSF"
  index: 0
  width: 30
  height: 30
  darkCount: 0
  integration: 10
  cropfactor: 6
  zeropadding: 3
  affinity: 3
  functions:
  - expose
  - integrate
  - computeStrehl
